version: '3.8'

services:
  # Core Database Services
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: brainsait_agents
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: brainsait_test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  # Core Orchestration Agent
  masterlinc:
    build: 
      context: ./agents/masterlinc
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:brainsait_test@postgres:5432/brainsait_agents
      - REDIS_URL=redis://redis:6379/0
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./agents/masterlinc:/app
      - ./shared:/app/shared
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
  
  # Authentication Service
  authlinc:
    build: ./agents/authlinc
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:brainsait_test@postgres:5432/brainsait_agents
      - REDIS_URL=redis://redis:6379/1
      - MASTER_LINC_URL=http://masterlinc:8000
      - JWT_SECRET=dev_jwt_secret_change_in_production
    depends_on:
      - masterlinc
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: brainsait_linc_network
